# Generated by Django 3.2.5 on 2021-09-06 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('booknumber', models.IntegerField(blank=True, default=None, null=True)),
                ('author', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('date', models.DateField(blank=True)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='issuebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.CharField(max_length=10)),
                ('sname', models.CharField(max_length=20)),
                ('bookname', models.CharField(max_length=100)),
                ('booknumber', models.IntegerField(blank=True, default=None, null=True)),
                ('author', models.CharField(max_length=50)),
                ('issuedate', models.DateField(blank=True)),
                ('returndate', models.DateField(blank=True)),
                ('aquantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='returnbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.CharField(max_length=10)),
                ('sname', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('bookname', models.CharField(max_length=20)),
                ('booknumber', models.IntegerField(blank=True, default=None, null=True)),
                ('author', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('issuedate', models.DateField(blank=True)),
                ('returningdate', models.DateField(blank=True)),
                ('returneddate', models.DateField(blank=True)),
                ('latefee', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='libraryuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
